import type { WikiArticle } from "../types";

export const sigmaAlgebra: WikiArticle = {
  conceptId: "sigma-algebra",
  summary:
    "A $\\sigma$-algebra is the collection of subsets we are allowed to assign probability to. On a finite sample space it is uninteresting — take every subset. On an infinite one it is unavoidable: there exist sets so pathological that no consistent notion of size can be assigned to them, and the $\\sigma$-algebra is how we exclude them.",
  sections: [
    {
      heading: "Definition",
      blocks: [
        {
          kind: "prose",
          text: "A collection $\\mathcal{F}$ of subsets of $\\Omega$ is a $\\sigma$-algebra when it satisfies three closure conditions:",
        },
        {
          kind: "list",
          ordered: true,
          items: [
            "$\\Omega \\in \\mathcal{F}$ — the whole space is measurable.",
            "$A \\in \\mathcal{F} \\Rightarrow A^{c} \\in \\mathcal{F}$ — closed under complement.",
            "$A_1, A_2, \\ldots \\in \\mathcal{F} \\Rightarrow \\bigcup_{i=1}^{\\infty} A_i \\in \\mathcal{F}$ — closed under **countable** union.",
          ],
        },
        {
          kind: "prose",
          text: "Intersections come free: De Morgan's laws build them from complements and unions, so $\\mathcal{F}$ is closed under countable intersection as well. Together these say that any event you can describe using countably many logical operations on measurable events is itself measurable.",
        },
        {
          kind: "callout",
          tone: "insight",
          title: "The conditions are exactly what probability needs",
          text: "They are not arbitrary axioms — each corresponds to a rule we want. Complements give $P(A^{c}) = 1 - P(A)$. Countable unions give countable additivity, which is what supports limits. And $\\Omega \\in \\mathcal{F}$ gives normalisation. A collection failing any of them would leave some perfectly natural probability question undefined.",
        },
      ],
    },
    {
      heading: "Why countable and not arbitrary",
      blocks: [
        {
          kind: "callout",
          tone: "warning",
          title: "Uncountable unions break everything",
          text: "Every single point of $[0,1]$ has probability zero under the uniform distribution. The interval is the union of its points — an uncountable union — and has probability 1. If closure extended to uncountable unions with additivity, we would be forced to conclude that uncountably many zeros sum to one. Restricting to countable operations is exactly what avoids this, and it is the reason 'countably' appears in both the $\\sigma$-algebra definition and Kolmogorov's third axiom.",
        },
        {
          kind: "prose",
          text: "The deeper reason a $\\sigma$-algebra is needed at all is the existence of non-measurable sets. Using the axiom of choice one can construct a subset of $[0,1]$ — the Vitali set — that cannot be assigned any length consistent with translation invariance and countable additivity. Such sets are not merely awkward to measure; assigning them any value at all produces a contradiction. The $\\sigma$-algebra is the formal device for leaving them out.",
        },
      ],
    },
    {
      heading: "The ones that matter",
      blocks: [
        {
          kind: "table",
          headers: ["$\\sigma$-algebra", "Contents", "Used for"],
          rows: [
            ["Trivial: $\\{\\varnothing, \\Omega\\}$", "nothing but the two extremes", "\"no information\""],
            ["Power set $2^{\\Omega}$", "every subset", "finite or countable $\\Omega$"],
            [
              "Borel $\\mathcal{B}(\\mathbb{R})$",
              "generated by the open intervals",
              "real-valued random variables",
            ],
            [
              "$\\sigma(X)$",
              "generated by the preimages $\\{X \\in B\\}$",
              "\"the information in $X$\"",
            ],
          ],
        },
        {
          kind: "prose",
          text: "The Borel $\\sigma$-algebra is the standard choice on $\\mathbb{R}$: the smallest one containing every open interval. It contains every set you will ever write down — intervals, points, countable unions of these, open sets, closed sets — while excluding the pathological constructions. Measurability of a random variable means exactly that $\\{X \\le x\\} \\in \\mathcal{F}$ for every $x$, which is what makes $P(X \\le x)$, and hence the CDF, well defined.",
        },
      ],
    },
    {
      heading: "$\\sigma$-algebras as information",
      blocks: [
        {
          kind: "callout",
          tone: "insight",
          title: "The interpretation that makes this useful",
          text: "$\\sigma(X)$ — the $\\sigma$-algebra generated by $X$ — is the collection of events whose occurrence you could determine if you observed $X$. A bigger $\\sigma$-algebra means more information. This is what makes filtrations possible: an increasing family $\\mathcal{F}_1 \\subseteq \\mathcal{F}_2 \\subseteq \\cdots$ models information accumulating over time, and it is the setting in which martingales, stopping times, and stochastic processes are defined.",
        },
        {
          kind: "prose",
          text: "It also gives the rigorous definition of conditional expectation. $\\mathbb{E}[X \\mid \\mathcal{G}]$ is the best prediction of $X$ using only the information in $\\mathcal{G}$ — formally, the $\\mathcal{G}$-measurable random variable agreeing with $X$ on average over every event in $\\mathcal{G}$. The tower property then reads as: predicting with less information, having predicted with more, gives the same answer as predicting with less directly.",
        },
        {
          kind: "callout",
          tone: "warning",
          title: "When you can safely ignore all of this",
          text: "For a finite or countable sample space, take $\\mathcal{F} = 2^{\\Omega}$ and nothing is lost. Every subset is measurable, the machinery is vacuous, and no result in elementary probability changes. The apparatus earns its place only for uncountable spaces, continuous-time processes, and conditional expectation given a general $\\sigma$-algebra.",
        },
      ],
    },
  ],
  references: [
    { source: "Billingsley, Probability and Measure", locator: "§1–3" },
    { source: "Casella & Berger, Statistical Inference", locator: "§1.2.1" },
    { source: "Williams, Probability with Martingales", locator: "Ch. 1–2" },
    { source: "Mathlingo assessment bank", locator: "assessments/foundations-of-probability.md" },
  ],
};
