import type { WikiArticle } from "../types";

export const filtrationsAndAdaptedProcessesWiki: WikiArticle = {
  conceptId: "filtrations-and-adapted-processes",
  summary:
    "A filtration $\\{\\mathcal F_t\\}$ is a growing family of $\\sigma$-algebras that formalizes " +
    "'everything observable by time $t$', and a process is adapted if it uses only information " +
    "available at that instant — it cannot peek at the future. These two definitions are almost " +
    "entirely bookkeeping, but the rest of stochastic calculus leans on them constantly: every " +
    "martingale, every Itô integral, and every no-arbitrage argument is stated relative to a filtration.",

  sections: [
    {
      heading: "Filtrations: information that only grows",
      blocks: [
        {
          kind: "formula",
          latex: "\\mathcal F_s \\subseteq \\mathcal F_t \\quad \\text{for all } s < t",
          caption: "A filtration is an increasing family of σ-algebras indexed by time",
        },
        {
          kind: "prose",
          text:
            "Each $\\mathcal F_t$ is a $\\sigma$-algebra — a collection of events, closed under " +
            "complement and countable union, for which 'has this event happened by time $t$?' is a " +
            "well-defined yes/no question. The inclusion $\\mathcal F_s \\subseteq \\mathcal F_t$ encodes " +
            "the one property that makes 'time' meaningful here: nothing is ever forgotten. Once an event " +
            "is resolvable at time $s$, it stays resolvable at every later time $t$.",
        },
        {
          kind: "definitions",
          items: [
            {
              term: "Natural (Brownian) filtration",
              description:
                "$\\mathcal F_t^W = \\sigma(W_s : s \\le t)$ — the $\\sigma$-algebra generated by the path of $W$ up to time $t$. Unless stated otherwise, this is the filtration used throughout the rest of this domain.",
            },
            {
              term: "$\\mathcal F_t$-measurable",
              description:
                "A random variable $X$ is $\\mathcal F_t$-measurable if its value can be determined from the information in $\\mathcal F_t$ — informally, if you can compute $X$ once you know everything that has happened up to time $t$.",
            },
          ],
        },
      ],
    },

    {
      heading: "Adapted processes: no peeking at the future",
      blocks: [
        {
          kind: "formula",
          latex: "X_t \\text{ is adapted to } \\{\\mathcal F_t\\} \\iff X_t \\text{ is } \\mathcal F_t\\text{-measurable for every } t",
        },
        {
          kind: "prose",
          text:
            "A process $X_t$ is adapted if, at every instant $t$, its current value is determined by " +
            "information already available at time $t$ — never by anything that happens after $t$. This " +
            "is the formal statement of a requirement that shows up everywhere: a trading strategy can be " +
            "based on prices observed so far, not on tomorrow's closing price; an integrand in a " +
            "stochastic integral must be adapted or the integral has no sensible interpretation as " +
            "something a real agent could compute.",
        },
        {
          kind: "table",
          headers: ["Process", "Adapted to $\\mathcal F_t^W$?", "Why"],
          rows: [
            ["$W_t$ itself", "Yes", "$W_t$ is trivially determined by the path up to time t"],
            ["$\\max_{s \\le t} W_s$", "Yes", "Computable from the path observed up to time t"],
            ["$W_{t+1}$", "No", "Requires information one time unit in the future"],
            ["$\\max_{s \\le T} W_s$ for fixed future $T$, viewed as a process in $t < T$", "No", "Depends on the whole path up to $T$, not just up to $t$"],
          ],
        },
        {
          kind: "callout",
          tone: "insight",
          title: "Adapted is what 'non-anticipating' means, made precise",
          text:
            "Later articles describe the Itô integral's integrand as 'non-anticipating', and describe a " +
            "hedging strategy as usable 'because it only depends on information available so far'. Both " +
            "phrases are informal restatements of adaptedness. Having the definition here means those " +
            "articles can invoke 'adapted' as a single precise word instead of re-explaining the idea " +
            "each time.",
        },
      ],
    },

    {
      heading: "Why the filtration matters, not just the process",
      blocks: [
        {
          kind: "prose",
          text:
            "The same process can be a martingale with respect to one filtration and fail to be one with " +
            "respect to a coarser or finer one — the martingale property is always stated 'with respect " +
            "to $\\{\\mathcal F_t\\}$', never in isolation, precisely because it is a statement about what " +
            "conditioning on that filtration's information does to the process's expected future value. " +
            "The natural filtration $\\mathcal F_t^W$ is the smallest filtration that makes $W_t$ adapted, " +
            "which is why it is the default choice — it encodes exactly the Brownian path and nothing " +
            "extra.",
        },
      ],
    },
  ],

  references: [
    { source: "Shreve, Stochastic Calculus for Finance II", locator: "§1.2, §3.3, Information and filtrations" },
    { source: "Øksendal, Stochastic Differential Equations", locator: "Ch. 3, Itô Integrals — preliminaries on filtrations" },
  ],
};
