import type { WikiArticle } from "../types";

export const martingaleRepresentationTheoremWiki: WikiArticle = {
  conceptId: "martingale-representation-theorem",
  summary:
    "In a Brownian filtration, every martingale is an Itô integral — no other kind exists. That single " +
    "structural fact, not any pricing formula, is what actually guarantees a hedge is always available: " +
    "the adapted integrand the theorem produces literally is the number of shares to hold at each " +
    "instant, which is why this theorem is the rigorous content behind 'markets are complete'.",

  sections: [
    {
      heading: "The statement",
      blocks: [
        {
          kind: "prose",
          text:
            "Fix the filtration generated by a Brownian motion $W_t$, $\\mathcal F_t = \\sigma(W_s : s " +
            "\\le t)$. Let $M_t$ be any martingale with respect to this filtration, with $E[M_t^2] < " +
            "\\infty$. The theorem says $M_t$ is not merely *representable* as an Itô integral — every " +
            "such martingale *is* one, uniquely.",
        },
        {
          kind: "formula",
          latex: "M_t = M_0 + \\int_0^t \\Delta_s \\, dW_s",
          caption: "for some adapted, square-integrable process Δ_s, unique up to a set of measure zero",
        },
        {
          kind: "callout",
          tone: "insight",
          title: "This is a statement about the filtration, not about M",
          text:
            "It is tempting to read this as a fact about which martingales happen to be Itô integrals. " +
            "It is really a fact about the Brownian filtration: because $\\mathcal F_t$ contains no " +
            "information beyond what $W$ itself reveals, there is nothing left for a martingale to " +
            "depend on except the path of $W$, and an Itô integral against $dW_s$ is exactly the general " +
            "form that dependence can take. A martingale adapted to a *richer* filtration — one carrying " +
            "an independent jump process, say — need not have this representation at all.",
        },
      ],
    },

    {
      heading: "Where the ingredients come from",
      blocks: [
        {
          kind: "prose",
          text:
            "Every piece of this theorem was assembled in earlier articles. The Itô integral article " +
            "defined $\\int \\Delta_s\\, dW_s$ and showed it is always a martingale — that gave one " +
            "direction, that every Itô integral is a martingale. This theorem is the converse, and by " +
            "far the harder direction: that the class of Itô integrals is not merely *a* family of " +
            "martingales in this filtration, it is *the entire family*, with nothing left over.",
        },
        {
          kind: "definitions",
          items: [
            {
              term: "Δ_s (the representing process)",
              description:
                "Not given in closed form by the theorem — its existence is guaranteed abstractly, and finding it explicitly is a separate problem (often solved via the Clark-Ocone formula or a PDE, in the pricing application below via Δ = ∂V/∂S).",
            },
            {
              term: "Uniqueness",
              description: "If two adapted processes both represent the same martingale, they agree except on a set of (time × probability) measure zero — the Itô isometry makes this precise.",
            },
          ],
        },
      ],
    },

    {
      heading: "Why this matters: hedging and completeness",
      blocks: [
        {
          kind: "prose",
          text:
            "Recall the Black-Scholes-Merton hedging argument: a replicating portfolio holding " +
            "$\\Delta = \\partial V/\\partial S$ shares of stock was constructed by differentiating a " +
            "known closed-form price $V(S,t)$. That works because Black-Scholes happens to have a " +
            "closed form. The martingale representation theorem removes that dependence entirely: for " +
            "*any* attainable claim, not just ones with closed-form prices, the discounted price process " +
            "$e^{-rt}V_t$ is a martingale under the risk-neutral measure, so this theorem guarantees some " +
            "adapted $\\Delta_t$ exists with $e^{-rt}V_t = V_0 + \\int_0^t \\Delta_s\\, d(e^{-rs}S_s)$ — " +
            "a replicating trading strategy, whether or not anyone can write $V$ down in closed form.",
        },
        {
          kind: "callout",
          tone: "warning",
          title: "Existence is not the same as a formula",
          text:
            "The theorem is a pure existence statement — it proves a hedge exists without constructing " +
            "it. This is exactly why so much of computational finance (PDE solvers, Monte Carlo " +
            "Greeks, the Clark-Ocone formula) exists: to actually compute the $\\Delta_t$ this theorem " +
            "only promises. Knowing a perfect hedge exists and knowing what it is are different " +
            "problems, and the gap between them is most of applied derivatives pricing.",
        },
        {
          kind: "list",
          items: [
            "Market completeness — every contingent claim can be replicated by trading the underlying and a bond — is, in a single-Brownian-driver model, literally this theorem plus the existence of the risk-neutral measure from Girsanov's theorem: together they are the two halves of the Fundamental Theorem of Asset Pricing's completeness half.",
            "It fails when the filtration carries more randomness than the traded assets span — e.g. a jump-diffusion model driven by a Poisson process nobody can trade directly — which is exactly why jump-diffusion and stochastic-volatility markets are typically incomplete, and why 'the' hedge stops being unique.",
            "Combined with Girsanov, it is the standard route to proving completeness rigorously in continuous-time finance, rather than assuming it as Black-Scholes does implicitly.",
          ],
        },
      ],
    },
  ],

  references: [
    { source: "Shreve, Stochastic Calculus for Finance II", locator: "§5.3, Martingale Representation Theorem" },
    { source: "Karatzas & Shreve, Brownian Motion and Stochastic Calculus", locator: "§3.4, Martingale Representation" },
  ],
};
