import type { Item } from "../../../lib/assessment/types";
import { makeBuilders } from "../authoring";
import { EXPANSION } from "./source";

/** Probability 40-pass (part A): events and measures → CDFs. Weighted to the hard end. */
const { mcq, short, num } = makeBuilders(EXPANSION);

const s = (concept: string, slug: string, level: number, stem: string, a: string, b: string) =>
  short({ concept, slug, cognitive: level >= 8.5 ? "transfer" : "explain", level, seconds: level >= 9 ? 300 : 200, stem },
    [["main", a, 5, true], ["detail", b, 4, true]]);
const n = (concept: string, slug: string, level: number, stem: string, key: number, tol = 0.01) =>
  num({ concept, slug, cognitive: "apply", level, seconds: level >= 7 ? 90 : 25, stem }, key, tol);
const m = (concept: string, slug: string, level: number, stem: string, right: string, wrong: [string, string][]) =>
  mcq({ concept, slug, cognitive: level <= 3 ? "recall" : "apply", level, seconds: 25, stem },
    right, wrong.map(([t, why], i) => [t, `${concept}-${slug}-${i}`, why] as [string, string, string]));

const PB = "pie-boole";
const SA = "sigma-algebra";
const AX = "axioms-of-probability";
const PF = "probability-function";
const CP = "conditional-probability";
const IS = "independence-set-theory";
const BR = "bayes-rule";
const MI = "mutual-independence";
const RV = "random-variables";
const DC = "discrete-vs-continuous-random-variables";
const CD = "cdf";

export const prFortyAItems: Item[] = [
  // --- pie-boole ------------------------------------------------------------------
  n(PB, "x4p-two", 4, "$P(A) = 0.5$, $P(B) = 0.4$ and $P(A \\cap B) = 0.2$. Compute $P(A \\cup B)$.", 0.7, 0.001),
  n(PB, "x4p-three", 7, "Three events each have probability $0.3$, each pairwise intersection has probability $0.1$, and the triple intersection has probability $0.05$. Compute the probability of their union.", 0.65, 0.001),
  n(PB, "x4p-derange5", 8, "Five letters are put into five envelopes at random. What is the probability that no letter is in its correct envelope?", 0.3667, 0.001),
  n(PB, "x4p-surject", 8, "Use inclusion–exclusion to count the functions from a $5$-element set onto a $3$-element set.", 150),
  s(PB, "x4p-bonferroni", 8.5, "State the Bonferroni inequalities and explain the pattern they follow.",
    "Truncating the inclusion–exclusion sum after an odd number of terms gives an upper bound on $P(\\bigcup A_i)$, and after an even number gives a lower bound.",
    "E.g. $S_1 - S_2 \\le P(\\bigcup A_i) \\le S_1$, where $S_k$ is the sum of $k$-fold intersection probabilities; Boole's inequality is the first upper bound."),
  n(PB, "x4p-lower", 8.5, "Ten events each have probability $0.05$, and every pairwise intersection has probability $0.002$. Compute the Bonferroni lower bound $S_1 - S_2$ on their union.", 0.41, 0.001),
  n(PB, "x4p-suits", 9, "What is the probability that a random $5$-card poker hand is missing at least one suit?", 0.7363, 0.001),
  s(PB, "x4p-union-bound", 9, "Boole's inequality can exceed $1$ when there are many events. Why is the union bound still so widely used?",
    "It needs no knowledge of dependence and is nearly tight when the events are rare and nearly disjoint, which is exactly when you want to show that no bad event is likely.",
    "Examples: Bonferroni corrections, bounding the probability that any of many estimates fails (PAC learning), and algorithm analysis."),
  n(PB, "x4p-d10", 9.5, "What is the probability that a random permutation of $10$ items has no fixed points?", 0.36788, 0.0001),
  s(PB, "x4p-derive", 9.5, "Derive the probability that a random permutation of $n$ items has no fixed points.",
    "Let $A_i$ be the event that $i$ is fixed; any $k$ specified items are all fixed with probability $(n - k)!/n!$, and there are $\\binom{n}{k}$ such sets.",
    "Inclusion–exclusion gives $P(\\text{no fixed point}) = \\sum_{k=0}^n(-1)^k/k!$, which tends to $e^{-1}$ very quickly."),

  // --- sigma-algebra ----------------------------------------------------------------
  m(SA, "x4p-gen", 4, "The smallest σ-algebra on $\\Omega$ containing an event $A$ is:", "$\\lbrace\\emptyset, A, A^c, \\Omega\\rbrace$",
    [["$\\lbrace A\\rbrace$", "Must contain complements, $\\emptyset$ and $\\Omega$."], ["$\\lbrace\\emptyset, A, \\Omega\\rbrace$", "Missing $A^c$."], ["The power set of $\\Omega$", "Not the smallest."]]),
  n(SA, "x4p-partition", 7, "How many sets are in the σ-algebra generated by a partition of $\\Omega$ into $4$ blocks?", 16),
  n(SA, "x4p-bell", 7.5, "How many different σ-algebras are there on a $3$-element set?", 5),
  m(SA, "x4p-vitali", 8, "Why isn't every subset of $\\mathbb{R}$ made an event for the uniform distribution on $[0, 1]$?", "No countably additive, translation-invariant measure can be defined on all subsets (Vitali's construction)",
    [["It would make computation too slow", "The obstruction is mathematical."], ["The power set is countable", "It isn't."], ["Probabilities would exceed $1$", "Not the issue."]]),
  s(SA, "x4p-algebra", 8, "What's the difference between an algebra of sets and a σ-algebra, and why do countable unions matter in probability?",
    "An algebra is closed under complements and finite unions; a σ-algebra is closed under countable unions.",
    "Countable operations are needed for limits: events like $\\lbrace X_n \\to X\\rbrace$ or $\\limsup A_n$, and countable additivity. Finite unions of intervals form an algebra but not a σ-algebra."),
  m(SA, "x4p-borel", 8.5, "The Borel σ-algebra on $\\mathbb{R}$ is generated by:", "The open sets (equivalently, the half-lines $(-\\infty, x]$)",
    [["All subsets of $\\mathbb{R}$", "That's the power set."], ["The singletons only", "Countable/co-countable sets are too few."], ["The rational numbers", "No."]]),
  s(SA, "x4p-measurable", 8.5, "What does it mean for a random variable to be measurable, and why is it required?",
    "$X$ is measurable if $X^{-1}(B)$ is an event for every Borel set $B$.",
    "Otherwise $P(X \\in B)$ might be undefined; measurability is exactly what lets $X$ have a distribution."),
  s(SA, "x4p-sigma-x", 9, "Explain $\\sigma(X)$, the σ-algebra generated by $X$, and its interpretation as information.",
    "$\\sigma(X) = \\lbrace X^{-1}(B)\\rbrace$ contains exactly the events whose occurrence can be decided by observing $X$.",
    "By the Doob–Dynkin lemma, $Y$ is $\\sigma(X)$-measurable if and only if $Y = g(X)$ for some measurable $g$ — “knowing $X$ determines $Y$.”"),
  m(SA, "x4p-union", 9, "Is the union of two σ-algebras on the same set always a σ-algebra?", "No — on $\\lbrace 1, 2, 3\\rbrace$, $\\lbrace\\emptyset, \\lbrace 1\\rbrace, \\lbrace 2, 3\\rbrace, \\Omega\\rbrace \\cup \\lbrace\\emptyset, \\lbrace 2\\rbrace, \\lbrace 1, 3\\rbrace, \\Omega\\rbrace$ lacks $\\lbrace 1, 2\\rbrace$",
    [["Yes, always", "Counterexample exists."], ["Only for finite sets", "Fails on finite sets too."], ["Yes, if both contain $\\Omega$", "They always do."]]),
  s(SA, "x4p-pi-lambda", 9.5, "State Dynkin's π–λ theorem and explain how it shows that a CDF determines a distribution.",
    "If a π-system (closed under finite intersections) is contained in a λ-system, then so is the σ-algebra it generates.",
    "The sets on which two probability measures agree form a λ-system; if they agree on the π-system of half-lines $(-\\infty, x]$ (equal CDFs), they agree on all Borel sets."),

  // --- axioms-of-probability ------------------------------------------------------------
  n(AX, "x4p-complement", 4, "$P(A) = 0.35$. Use the axioms to find $P(A^c)$.", 0.65, 0.001),
  m(AX, "x4p-monotone", 7, "Which of these follows from the axioms?", "If $A \\subseteq B$ then $P(A) \\le P(B)$",
    [["$P(A \\cup B) = P(A) + P(B)$ always", "Only for disjoint events."], ["$P(A \\cap B) = P(A)P(B)$", "Only under independence."], ["$P(A) > 0$ for every non-empty $A$", "Non-empty events can have probability $0$."]]),
  s(AX, "x4p-empty", 8, "Prove $P(\\emptyset) = 0$ from Kolmogorov's axioms.",
    "Write $\\Omega = \\Omega \\cup \\emptyset \\cup \\emptyset \\cup \\cdots$, a countable disjoint union; countable additivity gives $P(\\Omega) = P(\\Omega) + \\sum P(\\emptyset)$.",
    "Since $P(\\Omega) = 1$ is finite, $\\sum P(\\emptyset) = 0$, so $P(\\emptyset) = 0$."),
  s(AX, "x4p-continuity", 8, "Prove continuity from below: if $A_1 \\subseteq A_2 \\subseteq \\cdots$ and $A = \\bigcup A_n$, then $P(A_n) \\to P(A)$.",
    "Let $B_1 = A_1$ and $B_n = A_n \\setminus A_{n-1}$. These are disjoint, $A_n = B_1 \\cup \\cdots \\cup B_n$, and $A = \\bigcup B_n$.",
    "Countable additivity gives $P(A) = \\sum_{k=1}^\\infty P(B_k) = \\lim_n\\sum_{k=1}^nP(B_k) = \\lim_nP(A_n)$."),
  m(AX, "x4p-uniform-n", 8.5, "Why can't there be a uniform probability distribution on the natural numbers?", "Countable additivity would give $1 = \\sum_np$, which fails for every constant $p$",
    [["The natural numbers are uncountable", "They're countable."], ["Probabilities must be rational", "No."], ["It would violate monotonicity", "Not the issue."]]),
  n(AX, "x4p-limit", 8.5, "$P(X > n) = 2^{-n}$ for every integer $n$. Using continuity from above, compute $P(X > n \\text{ for all } n)$.", 0),
  s(AX, "x4p-finite", 9, "Contrast finite with countable additivity, and describe de Finetti's objection.",
    "Kolmogorov requires countable additivity; de Finetti argued only finite additivity is justified by coherence (betting) arguments.",
    "Finitely additive probabilities allow e.g. a “uniform” distribution on $\\mathbb{N}$, but lose continuity and most limit theorems, so standard theory adopts countable additivity."),
  n(AX, "x4p-frechet-lo", 9, "$P(A) = 0.7$ and $P(B) = 0.6$. What is the smallest possible value of $P(A \\cap B)$?", 0.3, 0.001),
  n(AX, "x4p-frechet-hi", 9, "Same: what is the largest possible value of $P(A \\cap B)$?", 0.6, 0.001),
  s(AX, "x4p-equiv", 9.5, "Show that countable additivity is equivalent to finite additivity plus continuity at $\\emptyset$ ($A_n \\downarrow \\emptyset \\Rightarrow P(A_n) \\to 0$).",
    "Given countable additivity, continuity follows by writing $A_1$ as the disjoint union of the $A_n \\setminus A_{n+1}$ (tail sums vanish).",
    "Conversely, for disjoint $B_k$, $C_n = \\bigcup_{k>n}B_k \\downarrow \\emptyset$, and finite additivity gives $P(\\bigcup B_k) = \\sum_{k \\le n}P(B_k) + P(C_n) \\to \\sum_kP(B_k)$."),

  // --- probability-function ----------------------------------------------------------------
  n(PF, "x4p-loaded", 4, "A die is loaded so that $P(k) \\propto k$. Compute $P(6)$.", 0.2857, 0.001),
  n(PF, "x4p-even", 7, "For the same die, compute $P(\\text{even})$.", 0.5714, 0.001),
  n(PF, "x4p-basel", 8, "$P(n) = c/n^2$ for $n = 1, 2, \\ldots$. Compute $c$.", 0.6079, 0.001),
  m(PF, "x4p-harmonic", 8, "Setting $P(\\lbrace n\\rbrace) = c/n$ on the positive integers:", "Can't define a probability function, because $\\sum1/n$ diverges",
    [["Works with $c = 1$", "The sum diverges."], ["Works with $c = 6/\\pi^2$", "That's for $1/n^2$."], ["Works for large enough $c$", "No constant fixes divergence."]]),
  n(PF, "x4p-basel-even", 8.5, "With $P(n) = c/n^2$, compute $P(n \\text{ is even})$.", 0.25, 0.001),
  s(PF, "x4p-uncountable", 8.5, "Why isn't a probability function on an uncountable space determined by the probabilities of single outcomes?",
    "For continuous distributions every singleton has probability $0$, and countable additivity doesn't extend to uncountable unions, so the singletons say nothing about $P([0, \\tfrac12])$.",
    "The measure has to be specified on a σ-algebra, e.g. through a CDF or density."),
  n(PF, "x4p-dice", 9, "Two fair dice are rolled. Given that at least one die shows $3$, what is the probability the sum is $7$?", 0.1818, 0.001),
  s(PF, "x4p-mass-measure", 9, "Distinguish a probability mass function on outcomes from a probability measure on events.",
    "A pmf assigns probabilities to outcomes and only determines a measure on countable spaces, via $P(A) = \\sum_{\\omega \\in A}p(\\omega)$.",
    "A probability measure is defined on a σ-algebra of events; for continuous or mixed distributions it cannot be recovered from outcome probabilities."),
  n(PF, "x4p-benford", 9.5, "Under Benford's law, $P(\\text{first digit} = d) = \\log_{10}(1 + 1/d)$. Compute $P(\\text{first digit} \\le 3)$.", 0.6021, 0.001),
  s(PF, "x4p-benford-why", 9.5, "Explain why Benford's law is scale-invariant.",
    "Benford's law is equivalent to $\\log_{10}X$ being uniform modulo $1$. Multiplying the data by $c$ shifts $\\log_{10}X$ by $\\log_{10}c$, and a uniform distribution on the circle is unchanged by a shift.",
    "So the first-digit law is the same in any units; it's the only scale-invariant first-digit law."),

  // --- conditional-probability ---------------------------------------------------------------
  n(CP, "x4p-basic", 4, "$P(A \\cap B) = 0.12$ and $P(B) = 0.4$. Compute $P(A \\mid B)$.", 0.3, 0.001),
  n(CP, "x4p-boys", 7, "A family has two children, at least one of whom is a boy. What is the probability both are boys?", 0.3333, 0.001),
  n(CP, "x4p-box", 7, "Three boxes contain two gold coins, two silver coins, and one of each. You pick a box at random and draw a gold coin. What is the probability the other coin in the box is gold?", 0.6667, 0.001),
  n(CP, "x4p-tuesday", 8, "A family has two children, at least one of whom is a boy born on a Tuesday. What is the probability both are boys?", 0.4815, 0.001),
  n(CP, "x4p-monty4", 8, "Monty Hall with $4$ doors: after you pick, the host opens one goat door and you switch to one of the other two closed doors at random. What is your probability of winning?", 0.375, 0.001),
  s(CP, "x4p-tuesday-why", 8.5, "Why does “born on a Tuesday” change the answer to the two-boys problem?",
    "The more specific condition comes close to identifying a particular child; of the $27$ equally likely cases, $13$ have two boys.",
    "The more specific the detail, the closer the answer gets to $\\tfrac12$ (the answer if a specific child were named)."),
  n(CP, "x4p-aces", 8.5, "Two cards are dealt from a standard deck. Given at least one is an ace, what is the probability both are aces?", 0.0303, 0.0005),
  n(CP, "x4p-ace-spades", 9, "Two cards are dealt. Given one of them is the ace of spades, what is the probability both are aces?", 0.0588, 0.0005),
  s(CP, "x4p-borel", 9, "Explain the Borel–Kolmogorov paradox.",
    "Conditioning on an event of probability zero isn't well defined by the ratio formula; it depends on the family of events used to approximate it.",
    "For a uniform point on a sphere, conditioning on a great circle gives a uniform distribution if the circle is the equator, but a non-uniform one if it's a meridian approached through longitude."),
  s(CP, "x4p-measure", 9.5, "Show that $P(\\cdot \\mid B)$ is itself a probability measure when $P(B) > 0$.",
    "It's non-negative, and $P(\\Omega \\mid B) = P(B)/P(B) = 1$.",
    "For disjoint $A_i$, the sets $A_i \\cap B$ are disjoint, so $P(\\bigcup A_i \\mid B) = \\sum P(A_i \\cap B)/P(B) = \\sum P(A_i \\mid B)$. Every probability rule therefore holds conditionally."),

  // --- independence-set-theory ---------------------------------------------------------------
  n(IS, "x4p-union", 4, "$A$ and $B$ are independent with $P(A) = 0.3$ and $P(B) = 0.5$. Compute $P(A \\cup B)$.", 0.65, 0.001),
  m(IS, "x4p-comp", 7, "If $A$ and $B$ are independent, then $A$ and $B^c$ are:", "Also independent",
    [["Dependent", "$P(A \\cap B^c) = P(A) - P(A)P(B) = P(A)P(B^c)$."], ["Disjoint", "No."], ["Independent only if $P(A) = \\tfrac12$", "Always independent."]]),
  n(IS, "x4p-dice", 8, "Two dice: $A$ = the first die is even, $B$ = the sum is $7$. Compute $P(A \\cap B)$ (and compare it with $P(A)P(B)$).", 0.08333, 0.0005),
  s(IS, "x4p-disjoint", 8, "Can two disjoint events with positive probabilities be independent?",
    "No: $P(A \\cap B) = 0$ but $P(A)P(B) > 0$.",
    "Disjoint events are strongly dependent — knowing $A$ occurred tells you $B$ didn't."),
  n(IS, "x4p-null", 8.5, "$P(A) = 0$. Compute $P(A \\cap B) - P(A)P(B)$ for an arbitrary event $B$.", 0),
  s(IS, "x4p-self", 8.5, "Show that an event independent of itself has probability $0$ or $1$.",
    "$P(A) = P(A \\cap A) = P(A)^2$, so $P(A) \\in \\lbrace 0, 1\\rbrace$.",
    "This is the mechanism behind Kolmogorov's 0–1 law: tail events are independent of themselves."),
  n(IS, "x4p-div12", 9, "Pick uniformly from $\\lbrace 1, \\ldots, 12\\rbrace$. $A$ = divisible by $2$, $B$ = divisible by $3$. Compute $P(A \\cap B) - P(A)P(B)$.", 0),
  n(IS, "x4p-div10", 9, "Same, but from $\\lbrace 1, \\ldots, 10\\rbrace$. Compute $P(A \\cap B) - P(A)P(B)$.", -0.05, 0.001),
  s(IS, "x4p-cond-ind", 9, "Give an example where two events are conditionally independent but not independent.",
    "Pick a coin whose bias is random (fair or two-headed), then flip it twice: given the coin, the flips are independent.",
    "Marginally they're dependent: a first head makes the two-headed coin more likely, raising the chance of a second head."),
  s(IS, "x4p-measure-dep", 9.5, "Why is independence a property of the probability measure rather than of the events themselves?",
    "The same two events can satisfy $P(A \\cap B) = P(A)P(B)$ under one measure and fail it under another, e.g. after conditioning on new information.",
    "So updating beliefs (Bayesian conditioning) can create or destroy independence; exchangeable sequences are independent only conditionally on a latent parameter."),

  // --- bayes-rule ----------------------------------------------------------------------------
  n(BR, "x4p-5050", 4, "Sensitivity $0.9$, specificity $0.9$, prevalence $0.1$. Compute $P(\\text{disease} \\mid +)$.", 0.5, 0.001),
  n(BR, "x4p-rare", 7, "Prevalence $0.01$, sensitivity $0.99$, specificity $0.95$. Compute $P(\\text{disease} \\mid +)$.", 0.1667, 0.001),
  n(BR, "x4p-twice", 8, "Same test, applied twice with conditionally independent errors; both results are positive. Compute $P(\\text{disease} \\mid +, +)$.", 0.7984, 0.001),
  n(BR, "x4p-lrneg", 8, "Compute the likelihood ratio of a negative result, $(1 - \\text{sens})/\\text{spec}$, for that test.", 0.01053, 0.0002),
  s(BR, "x4p-odds", 8.5, "Write Bayes' rule in odds form and explain why it's convenient.",
    "Posterior odds = prior odds × likelihood ratio, where the likelihood ratio is $P(E \\mid H)/P(E \\mid H^c)$.",
    "Conditionally independent pieces of evidence multiply their likelihood ratios (add their log-LRs), making sequential updating simple."),
  n(BR, "x4p-dna", 8.5, "A DNA profile has match probability $10^{-6}$. With $5 \\times 10^6$ equally plausible sources and no other evidence, what is the probability a matching suspect is the source?", 0.1667, 0.001),
  s(BR, "x4p-base-rate", 9, "Explain base-rate neglect with an example, and why it matters in screening.",
    "People equate $P(+ \\mid D)$ with $P(D \\mid +)$, ignoring prevalence: with prevalence $1\\%$, even a $99\\%$-sensitive, $95\\%$-specific test gives only about $17\\%$ positive predictive value.",
    "Mass screening of low-prevalence populations produces mostly false positives, which is why confirmatory tests and targeting high-risk groups matter."),
  n(BR, "x4p-coins", 9, "Three coins — fair, two-headed, and one with $P(H) = 0.75$ — are equally likely to be picked. The chosen coin gives HH. Compute $P(\\text{two-headed} \\mid HH)$.", 0.5517, 0.001),
  n(BR, "x4p-next", 9.5, "Same setup: compute the probability the next flip is heads.", 0.8534, 0.001),
  s(BR, "x4p-correlated", 9.5, "Why can't you multiply the likelihood ratios of two positive tests if they share failure modes?",
    "Multiplying assumes the results are conditionally independent given disease status; if both tests react to the same interfering factor, a false positive on one makes a false positive on the other likely.",
    "The joint likelihood ratio is then much smaller than the product, and naive multiplication gives badly overconfident posteriors (common with repeated runs of the same assay)."),

  // --- mutual-independence --------------------------------------------------------------------
  m(MI, "x4p-def", 4, "Mutual independence of $A$, $B$ and $C$ requires:", "All three pairwise product rules and $P(A \\cap B \\cap C) = P(A)P(B)P(C)$",
    [["Only the triple product rule", "Pairwise rules are also needed."], ["Only pairwise independence", "The triple rule is also needed."], ["That the events are disjoint", "No."]]),
  n(MI, "x4p-count", 7, "How many product conditions must be checked for mutual independence of $4$ events?", 11),
  n(MI, "x4p-pairwise", 8, "Two fair coins: $A$ = first is H, $B$ = second is H, $C$ = both show the same face. Compute $P(A \\cap B \\cap C)$.", 0.25, 0.001),
  s(MI, "x4p-why", 8, "Explain why $A$, $B$ and $C$ from the previous question are pairwise but not mutually independent.",
    "Each pair has probability $\\tfrac14 = \\tfrac12 \\cdot \\tfrac12$, so they are pairwise independent.",
    "But $P(A \\cap B \\cap C) = \\tfrac14 \\ne \\tfrac18$: any two of the events determine the third."),
  n(MI, "x4p-atleast", 8.5, "Five mutually independent events each have probability $0.2$. Compute the probability that at least one occurs.", 0.6723, 0.001),
  n(MI, "x4p-series", 8.5, "A series system has $3$ independent components, each with reliability $0.9$. Compute the system reliability.", 0.729, 0.001),
  n(MI, "x4p-parallel", 9, "Two series pairs (each of two independent components with reliability $0.9$) are connected in parallel. Compute the system reliability.", 0.9639, 0.001),
  s(MI, "x4p-triple-only", 9, "Give an example where $P(A \\cap B \\cap C) = P(A)P(B)P(C)$ but the events are not pairwise independent.",
    "Two dice: $A$ = first die in $\\lbrace 1, 2, 3\\rbrace$, $B$ = first die in $\\lbrace 3, 4, 5\\rbrace$, $C$ = the sum is $9$. Then $P(A \\cap B \\cap C) = P(\\text{first } 3, \\text{second } 6) = \\tfrac1{36} = \\tfrac12 \\cdot \\tfrac12 \\cdot \\tfrac19$.",
    "But $P(A \\cap B) = \\tfrac16 \\ne \\tfrac14$, so the triple product rule alone doesn't imply independence."),
  n(MI, "x4p-ab", 9, "In that example, compute $P(A \\cap B)$.", 0.1667, 0.001),
  s(MI, "x4p-sigma", 9.5, "Why is independence of random variables defined through σ-algebras rather than single events?",
    "$X$ and $Y$ are independent when every event $\\lbrace X \\in A\\rbrace$ is independent of every event $\\lbrace Y \\in B\\rbrace$, i.e. $\\sigma(X)$ and $\\sigma(Y)$ are independent.",
    "This guarantees that functions $f(X)$ and $g(Y)$ are independent and makes mutual independence of many variables a statement about all joint events, not a few chosen ones."),

  // --- random-variables ----------------------------------------------------------------------
  m(RV, "x4p-def", 4, "Formally, a random variable is:", "A measurable function from the sample space to the real numbers",
    [["A number that changes randomly", "It's a deterministic function of the outcome."], ["A probability", "No."], ["An event", "No."]]),
  n(RV, "x4p-heads", 7, "$X$ is the number of heads in $3$ coin flips. How many outcomes make up the event $\\lbrace X = 2\\rbrace$?", 3),
  n(RV, "x4p-max", 8, "$X$ is the maximum of two fair dice. Compute $P(X = 4)$.", 0.1944, 0.001),
  n(RV, "x4p-absdiff0", 8, "$X = |D_1 - D_2|$ for two fair dice. Compute $P(X = 0)$.", 0.1667, 0.001),
  n(RV, "x4p-absdiff-e", 8.5, "Compute $\\mathbb{E}|D_1 - D_2|$ for two fair dice.", 1.9444, 0.001),
  s(RV, "x4p-neither", 8.5, "In what sense is a random variable “neither random nor a variable”?",
    "It's a fixed, deterministic function $X: \\Omega \\to \\mathbb{R}$; the randomness lives in which outcome $\\omega$ occurs.",
    "Its distribution is the pushforward of $P$ through $X$: $P_X(B) = P(X^{-1}(B))$."),
  s(RV, "x4p-pushforward", 9, "Explain the pushforward $P_X(B) = P(X^{-1}(B))$ and why different random variables can have the same distribution.",
    "The distribution only records how much probability $X$ sends to each Borel set, not which outcomes it came from.",
    "E.g. for a fair coin, $X$ = indicator of heads and $Y = 1 - X$ are both Bernoulli($\\tfrac12$) though $X \\ne Y$ for every outcome."),
  n(RV, "x4p-reflect", 9, "$X$ is uniform on $\\lbrace 1, \\ldots, 6\\rbrace$ and $Y = 7 - X$. Compute $P(X = Y)$.", 0),
  m(RV, "x4p-samedist", 9, "$X$ and $Y$ have the same distribution. Which must hold?", "$\\mathbb{E}[g(X)] = \\mathbb{E}[g(Y)]$ for every bounded measurable $g$",
    [["$X = Y$ almost surely", "No — see $X$ and $1 - X$ for a fair coin."], ["$P(X = Y) > 0$", "Not necessarily."], ["$X$ and $Y$ are independent", "No."]]),
  s(RV, "x4p-quantile", 9.5, "Explain why any distribution can be realised on $([0, 1], \\text{uniform})$ via its quantile function.",
    "With $U \\sim \\mathrm{Uniform}(0, 1)$ and the generalised inverse $F^{-1}(u) = \\inf\\lbrace x : F(x) \\ge u\\rbrace$, we have $F^{-1}(U) \\le x \\iff U \\le F(x)$, so $F^{-1}(U)$ has CDF $F$.",
    "This is inverse-transform sampling, and it works for discrete and mixed distributions thanks to the generalised inverse."),

  // --- discrete-vs-continuous-random-variables ---------------------------------------------------
  m(DC, "x4p-atom", 4, "A random variable with $P(X = x) > 0$ for some $x$:", "Isn't continuous — it has an atom at $x$",
    [["Must be discrete", "It could be mixed."], ["Has a density", "Atoms rule out a density."], ["Must be uniform", "No."]]),
  n(DC, "x4p-mixed-e", 7, "$X = 0$ with probability $0.3$; otherwise $X \\sim \\mathrm{Uniform}(0, 1)$. Compute $\\mathbb{E}[X]$.", 0.35, 0.001),
  n(DC, "x4p-mixed-cdf", 8, "For the same $X$, compute $P(X \\le 0.5)$.", 0.65, 0.001),
  m(DC, "x4p-cantor", 8, "The Cantor distribution is:", "Continuous (no atoms) but singular — it has no density",
    [["Discrete", "It has no atoms."], ["Absolutely continuous", "It has no density."], ["Uniform on $[0, 1]$", "It lives on the Cantor set."]]),
  s(DC, "x4p-lebesgue", 8.5, "Explain the Lebesgue decomposition of a distribution.",
    "Every distribution is a mixture of a discrete part (atoms), an absolutely continuous part (with a density) and a singular continuous part.",
    "The singular part is continuous but concentrated on a set of Lebesgue measure zero, like the Cantor distribution; most practical distributions have no singular part."),
  n(DC, "x4p-floor0", 8.5, "$X \\sim \\mathrm{Exp}(1)$ and $Y = \\lfloor X\\rfloor$. Compute $P(Y = 0)$.", 0.6321, 0.001),
  n(DC, "x4p-floor-e", 9, "Compute $\\mathbb{E}[Y]$ for $Y = \\lfloor X\\rfloor$ with $X \\sim \\mathrm{Exp}(1)$.", 0.582, 0.001),
  s(DC, "x4p-zero-prob", 9, "Why doesn't $P(X = x) = 0$ for a continuous $X$ mean that $x$ is impossible?",
    "Every value has probability $0$, yet some value occurs; probability zero means “almost never”, not “never”.",
    "Only sets of positive length carry probability; the uncountable sum of zero point probabilities isn't additive."),
  n(DC, "x4p-claim", 9, "A claim is $0$ with probability $0.8$; otherwise it's exponential with mean $1000$. Compute the variance of the claim amount.", 360000),
  s(DC, "x4p-mixed-lik", 9.5, "Why do mixed distributions (zero-inflation, censoring) matter in practice, and how is their likelihood written?",
    "Many measurements have point masses at boundaries — zero spending, detection limits, censored survival times — so neither a pmf nor a pdf alone describes them.",
    "The likelihood uses a pmf for the atoms and a density for the continuous part (a density with respect to counting plus Lebesgue measure), e.g. the Tobit model."),

  // --- cdf ---------------------------------------------------------------------------------------
  n(CD, "x4p-interval", 4, "$F(x) = 1 - e^{-2x}$ for $x \\ge 0$. Compute $P(1 < X \\le 2)$.", 0.117, 0.001),
  m(CD, "x4p-valid", 7, "A function $F$ is a valid CDF if and only if it is:", "Non-decreasing and right-continuous, with limits $0$ at $-\\infty$ and $1$ at $\\infty$",
    [["Continuous and increasing", "CDFs can jump and be flat."], ["Differentiable", "Not required."], ["Bounded by $1$", "Not sufficient."]]),
  n(CD, "x4p-median", 8, "$F(x) = x^2$ on $[0, 1]$. Compute the median.", 0.7071, 0.001),
  n(CD, "x4p-mean", 8, "For $F(x) = x^2$ on $[0, 1]$, compute $\\mathbb{E}[X] = \\int_0^1(1 - F(x))\\,dx$.", 0.6667, 0.001),
  s(CD, "x4p-tail", 8.5, "Show that $\\mathbb{E}[X] = \\int_0^\\infty P(X > x)\\,dx$ for non-negative $X$.",
    "Write $X = \\int_0^\\infty\\mathbf{1}(x < X)\\,dx$ and take expectations, swapping the expectation and the integral (Tonelli).",
    "The discrete version is $\\mathbb{E}[X] = \\sum_{k \\ge 1}P(X \\ge k)$ for non-negative integers."),
  n(CD, "x4p-max3", 8.5, "The maximum of $3$ independent $\\mathrm{Uniform}(0, 1)$ variables has CDF $x^3$. Compute $P(\\max > 0.8)$.", 0.488, 0.001),
  n(CD, "x4p-min3", 9, "Compute $P(\\min > 0.2)$ for the same $3$ uniforms.", 0.512, 0.001),
  s(CD, "x4p-right", 9, "Why is a CDF right-continuous but not necessarily left-continuous?",
    "$F(x) = P(X \\le x)$ and $\\bigcap_n(-\\infty, x + 1/n] = (-\\infty, x]$, so continuity from above gives $F(x + 1/n) \\to F(x)$.",
    "From the left, $\\bigcup_n(-\\infty, x - 1/n] = (-\\infty, x)$, so $F(x^-) = P(X < x)$; the jump $F(x) - F(x^-)$ is $P(X = x)$."),
  n(CD, "x4p-geninv", 9, "$P(X = 1) = 0.3$, $P(X = 2) = 0.5$ and $P(X = 3) = 0.2$. Compute the generalised inverse $F^{-1}(0.8) = \\inf\\lbrace x : F(x) \\ge 0.8\\rbrace$.", 2),
  s(CD, "x4p-dkw", 9.5, "State the Dvoretzky–Kiefer–Wolfowitz inequality and what it says about the empirical CDF.",
    "$P(\\sup_x|F_n(x) - F(x)| > \\varepsilon) \\le 2e^{-2n\\varepsilon^2}$ for every $n$ and every distribution.",
    "It gives uniform, distribution-free convergence (quantifying Glivenko–Cantelli) and simultaneous confidence bands $F_n \\pm \\sqrt{\\log(2/\\alpha)/(2n)}$."),
];
