import type { WikiArticle } from "../types";

export const woldDecompositionWiki: WikiArticle = {
  conceptId: "wold-decomposition",

  summary:
    "Wold's theorem is the reason AR and MA models are not just two convenient special cases but the " +
    "whole story: every purely non-deterministic, weakly stationary process can be written as an " +
    "infinite-order MA of white noise. AR(p) and ARMA(p, q) are not competitors to that " +
    "representation — they are finite, parsimonious ways of writing down the (generally infinite) MA(∞) " +
    "weights implied by the theorem.",

  sections: [
    {
      heading: "The statement",
      blocks: [
        {
          kind: "formula",
          latex: "Xₜ = μ + Σⱼ₌₀^∞ ψⱼεₜ₋ⱼ + κₜ,   ψ₀ = 1,   Σⱼ ψⱼ² < ∞",
          caption: "Any purely non-deterministic weakly stationary Xₜ decomposes into a linear (MA(∞)) combination of white noise εₜ, plus a deterministic component κₜ.",
        },
        {
          kind: "definitions",
          items: [
            {
              term: "εₜ, the innovations",
              description: "White noise, and specifically the one-step-ahead forecast errors: εₜ = Xₜ − E[Xₜ | Xₜ₋₁, Xₜ₋₂, …]. Not an arbitrary noise process — it is pinned down by the linear-prediction structure of Xₜ itself.",
            },
            {
              term: "κₜ, the deterministic component",
              description: "Perfectly predictable from the past — e.g. a deterministic sinusoid with a known phase. Zero for essentially every model this unit works with, which is why in practice the theorem is usually quoted with κₜ dropped.",
            },
            {
              term: "ψⱼ, the impulse response weights",
              description: "How much a shock at time t − j still influences Xₜ. Σψⱼ² < ∞ is exactly what makes the infinite sum a well-defined (finite-variance) random variable.",
            },
          ],
        },
      ],
    },

    {
      heading: "Why AR and MA both fit inside this",
      blocks: [
        {
          kind: "prose",
          text:
            "A finite MA(q) already has the Wold form directly — ψⱼ = θⱼ for j ≤ q and 0 afterward. A " +
            "stationary AR(1), unrolled, gave ψⱼ = φʲ — an MA(∞) with geometrically decaying weights. " +
            "Every stationary AR(p) and ARMA(p, q) process has an analogous MA(∞) expansion; the finite " +
            "AR or ARMA form is simply a more compact way to encode those infinitely many ψⱼ weights " +
            "using a handful of φ's and θ's rather than listing each ψⱼ separately.",
        },
        {
          kind: "table",
          headers: ["Representation", "Number of parameters", "What Wold guarantees"],
          rows: [
            ["MA(∞) (Wold form)", "Infinite, in general", "Exists for any stationary process — the universal representation"],
            ["MA(q)", "q + 1 (θ's and σ²)", "Exact when the true ψⱼ vanish beyond lag q — otherwise an approximation"],
            ["AR(p) or ARMA(p, q)", "p + q + 1", "A finite parametrisation whose implied ψⱼ can still decay forever — often far more parsimonious than a literal finite MA"],
          ],
        },
        {
          kind: "callout",
          tone: "insight",
          title: "This is why Box–Jenkins bothers with AR terms at all",
          text:
            "If every stationary process has an MA(∞) representation, one could in principle always fit " +
            "a (long, truncated) MA model. AR and ARMA exist because many processes with geometrically " +
            "decaying ψⱼ — the AR(1) case is the cleanest example — need infinitely many MA terms to " +
            "represent exactly, but only one or two AR terms to represent exactly. Wold's theorem " +
            "guarantees the MA(∞) form always exists; parsimony is the entire reason to prefer AR or " +
            "ARMA over writing it out.",
        },
      ],
    },

    {
      heading: "What the theorem does and doesn't promise",
      blocks: [
        {
          kind: "list",
          items: [
            "It guarantees existence of a linear representation, not that Xₜ is actually generated by a linear mechanism — a nonlinear process can still have a valid (if uninformative) Wold decomposition.",
            "It says nothing about which finite ARMA(p, q), if any, matches the true ψⱼ exactly; that is an empirical question answered by ACF/PACF shape and information criteria, not by the theorem itself.",
            "εₜ in the decomposition is specifically the linear innovation (the best linear one-step predictor's error), not necessarily the 'true' structural shock a scientific model of the process would name.",
            "It requires only weak stationarity and finite variance — no normality, and no assumption that the εₜ are independent, only uncorrelated.",
          ],
        },
        {
          kind: "callout",
          tone: "warning",
          title: "Existence is not the same as a finite-order model being adequate",
          text:
            "Because the theorem guarantees an infinite representation exists, it can be tempting to " +
            "treat any AR(p) or ARMA(p, q) fit as 'the' correct model. It is always an approximation to " +
            "the true (possibly infinite-order) ψⱼ sequence; residual diagnostics (Ljung–Box on the " +
            "fitted residuals) are what tell you whether the approximation is good enough, not the " +
            "theorem.",
        },
      ],
    },
  ],

  references: [
    { source: "Hamilton, Time Series Analysis", locator: "§4.1, The Wold Decomposition" },
    { source: "Brockwell & Davis, Time Series: Theory and Methods", locator: "§5.7, The Wold Decomposition" },
    { source: "Shumway & Stoffer, Time Series Analysis and Its Applications", locator: "§3.3, Autoregressive Moving Average Models" },
  ],
};
